# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'empregado', 'verbose_name_plural': 'empregados'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'registro de ponto', 'verbose_name_plural': 'registros de ponto'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='código celular'),
        ),
    ]
