# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160422_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ('time',), 'verbose_name': 'registro de ponto', 'verbose_name_plural': 'registros de ponto'},
        ),
        migrations.AddField(
            model_name='register',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
