# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160424_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='registered_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='register',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='register',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='longitude'),
        ),
    ]
