# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20160427_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome da empresa')),
                ('manager', models.ForeignKey(help_text='Gestor da loja', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, help_text='empresa', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.Company'),
            preserve_default=False,
        ),
    ]
